In [1]:
from System import System

In [2]:
sys = System(process_times=[3, 4, 5, 2, 3], degradation=[0]*5)
sys.simulate(warmup_time=0)

Writing M1 state at t=0, state=0
Writing M1 state at t=1, state=0
Writing M1 state at t=2, state=0
Writing M1 state at t=3, state=0
Writing M1 state at t=3, state=1
Writing M1 state at t=4, state=1
Writing M1 state at t=5, state=1
Writing M1 state at t=6, state=1
Writing M1 state at t=7, state=0
Writing M1 state at t=7, state=0
Writing M1 state at t=7, state=1
Writing M1 state at t=8, state=1
Writing M1 state at t=9, state=1
Writing M1 state at t=10, state=1
Writing M1 state at t=11, state=0
Writing M1 state at t=11, state=0
Writing M1 state at t=11, state=1
Writing M1 state at t=12, state=1
Writing M1 state at t=13, state=1
Writing M1 state at t=14, state=1
Writing M1 state at t=15, state=0
Writing M1 state at t=15, state=0
Writing M1 state at t=15, state=1
Writing M1 state at t=16, state=1
Writing M1 state at t=17, state=1
Writing M1 state at t=18, state=1
Writing M1 state at t=19, state=0
Writing M1 state at t=19, state=0
Writing M1 state at t=19, state=1
Writing M1 state at t=20, state=1
Writing M1 state at t=21, state=1
Writing M1 state at t=22, state=1
Writing M1 state at t=23, state=0
Writing M1 state at t=23, state=0
Writing M1 state at t=23, state=1
Writing M1 state at t=24, state=1
Writing M1 state at t=25, state=1
Writing M1 state at t=26, state=1
Writing M1 state at t=28, state=0
Writing M1 state at t=28, state=0
Writing M1 state at t=28, state=1
Writing M1 state at t=29, state=1
Writing M1 state at t=30, state=1
Writing M1 state at t=31, state=1
Writing M1 state at t=33, state=0
Writing M1 state at t=33, state=0
Writing M1 state at t=33, state=1
Writing M1 state at t=34, state=1
Writing M1 state at t=35, state=1
Writing M1 state at t=36, state=1
Writing M1 state at t=38, state=0
Writing M1 state at t=38, state=0
Writing M1 state at t=38, state=1
Writing M1 state at t=39, state=1
Writing M1 state at t=40, state=1
Writing M1 state at t=41, state=1
Writing M1 state at t=43, state=0
Writing M1 state at t=43, state=0
Writing M1 state at t=43, state=1
Writing M1 state at t=44, state=1
Writing M1 state at t=45, state=1
Writing M1 state at t=46, state=1
Writing M1 state at t=48, state=0
Writing M1 state at t=48, state=0
Writing M1 state at t=48, state=1
Writing M1 state at t=49, state=1
Writing M1 state at t=50, state=1
Writing M1 state at t=51, state=1
Writing M1 state at t=53, state=0
Writing M1 state at t=53, state=0
Writing M1 state at t=53, state=1
Writing M1 state at t=54, state=1
Writing M1 state at t=55, state=1
Writing M1 state at t=56, state=1
Writing M1 state at t=58, state=0
Writing M1 state at t=58, state=0
Writing M1 state at t=58, state=1
Writing M1 state at t=59, state=1
Writing M1 state at t=60, state=1
Writing M1 state at t=61, state=1
Writing M1 state at t=63, state=0
Writing M1 state at t=63, state=0
Writing M1 state at t=63, state=1
Writing M1 state at t=64, state=1
Writing M1 state at t=65, state=1
Writing M1 state at t=66, state=1
Writing M1 state at t=68, state=0
Writing M1 state at t=68, state=0
Writing M1 state at t=68, state=1
Writing M1 state at t=69, state=1
Writing M1 state at t=70, state=1
Writing M1 state at t=71, state=1
Writing M1 state at t=73, state=0
Writing M1 state at t=73, state=0
Writing M1 state at t=73, state=1
Writing M1 state at t=74, state=1
Writing M1 state at t=75, state=1
Writing M1 state at t=76, state=1
Writing M1 state at t=78, state=0
Writing M1 state at t=78, state=0
Writing M1 state at t=78, state=1
Writing M1 state at t=79, state=1
Writing M1 state at t=80, state=1
Writing M1 state at t=81, state=1
Writing M1 state at t=83, state=0
Writing M1 state at t=83, state=0
Writing M1 state at t=83, state=1
Writing M1 state at t=84, state=1
Writing M1 state at t=85, state=1
Writing M1 state at t=86, state=1
Writing M1 state at t=88, state=0
Writing M1 state at t=88, state=0
Writing M1 state at t=88, state=1
Writing M1 state at t=89, state=1
Writing M1 state at t=90, state=1
Writing M1 state at t=91, state=1
Writing M1 state at t=93, state=0
Writing M1 state at t=93, state=0
Writing M1 state at t=93, state=1
Writing M1 state at t=94, state=1
Writing M1 state at t=95, state=1
Writing M1 state at t=96, state=1
Writing M1 state at t=98, state=0
Writing M1 state at t=98, state=0
Writing M1 state at t=98, state=1
Writing M1 state at t=99, state=1
Simulation complete in 1.04s

In [3]:
sys.state_data

,time,M0 has part,b0 level,M1 has part,b1 level,M2 has part,b2 level,M3 has part,b3 level,M4 has part
0,NaN,0,0,0,0,0,0,0,0,0
1,NaN,0,0,0,0,0,0,0,0,0
2,NaN,0,0,0,0,0,0,0,0,0
3,NaN,0,0,1,0,0,0,0,0,0
4,NaN,0,0,1,0,0,0,0,0,0
5,NaN,0,0,1,0,0,0,0,0,0
6,NaN,0,1,1,0,0,0,0,0,0
7,NaN,0,1,1,1,0,0,0,0,0
8,NaN,0,0,1,0,1,0,0,0,0
9,NaN,0,1,1,0,1,0,0,0,0
10,NaN,0,1,1,0,1,0,0,0,0
11,NaN,0,1,1,1,1,0,0,0,0
12,NaN,0,1,1,1,1,0,0,0,0
13,NaN,0,1,1,1,1,1,0,0,0
14,NaN,0,1,1,0,1,0,1,0,0
15,NaN,0,1,1,1,1,0,1,0,0
16,NaN,0,1,1,1,1,0,0,1,0
17,NaN,0,1,1,1,1,0,0,0,1
18,NaN,NaN,NaN,1,1,1,0,1,0,1
19,NaN,0,1,1,1,1,0,1,0,1
20,NaN,0,1,1,1,1,0,0,1,1
21,NaN,0,1,1,1,1,0,0,0,1
22,NaN,NaN,NaN,1,1,1,0,0,0,1
23,NaN,0,1,1,1,1,0,1,0,1
24,NaN,0,1,1,1,1,0,1,0,1
25,NaN,0,1,1,1,1,0,0,1,1
26,NaN,NaN,NaN,1,1,1,0,0,0,1
27,NaN,NaN,NaN,NaN,NaN,1,0,0,0,1
28,NaN,0,1,1,1,1,0,1,0,1
29,NaN,0,1,1,1,1,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...
70,NaN,0,1,1,1,1,0,0,1,1
71,NaN,NaN,NaN,1,1,1,0,0,0,1
72,NaN,NaN,NaN,NaN,NaN,1,0,0,0,1
73,NaN,0,1,1,1,1,0,1,0,1
74,NaN,0,1,1,1,1,0,1,0,1
75,NaN,0,1,1,1,1,0,0,1,1
76,NaN,NaN,NaN,1,1,1,0,0,0,1
77,NaN,NaN,NaN,NaN,NaN,1,0,0,0,1
78,NaN,0,1,1,1,1,0,1,0,1
79,NaN,0,1,1,1,1,0,1,0,1
80,NaN,0,1,1,1,1,0,0,1,1
81,NaN,NaN,NaN,1,1,1,0,0,0,1
82,NaN,NaN,NaN,NaN,NaN,1,0,0,0,1
83,NaN,0,1,1,1,1,0,1,0,1
84,NaN,0,1,1,1,1,0,1,0,1
85,NaN,0,1,1,1,1,0,0,1,1
86,NaN,NaN,NaN,1,1,1,0,0,0,1
87,NaN,NaN,NaN,NaN,NaN,1,0,0,0,1
88,NaN,0,1,1,1,1,0,1,0,1
89,NaN,0,1,1,1,1,0,1,0,1
90,NaN,0,1,1,1,1,0,0,1,1
91,NaN,NaN,NaN,1,1,1,0,0,0,1
92,NaN,NaN,NaN,NaN,NaN,1,0,0,0,1
93,NaN,0,1,1,1,1,0,1,0,1
94,NaN,0,1,1,1,1,0,1,0,1
95,NaN,0,1,1,1,1,0,0,1,1
96,NaN,NaN,NaN,1,1,1,0,0,0,1
97,NaN,NaN,NaN,NaN,NaN,1,0,0,0,1
98,NaN,0,1,1,1,1,0,1,0,1
99,NaN,0,1,1,1,1,0,1,0,1

In [10]:
for m in range(5): print(m, sys.machines[m].parts_made)

0 22
1 20
2 18
3 17
4 17

In [2]:
# single machine production validation
pt = 5
sys = System(process_times=[pt], degradation=[0])
sys.simulate()
print('Parts made: {}'.format(sys.machines[0].parts_made))
print('Parts expected: {}'.format(99 // pt))

0 5
1 4
2 3
3 2
4 1
5 5
6 4
7 3
8 2
9 1
10 5
11 4
12 3
13 2
14 1
15 5
16 4
17 3
18 2
19 1
20 5
21 4
22 3
23 2
24 1
25 5
26 4
27 3
28 2
29 1
30 5
31 4
32 3
33 2
34 1
35 5
36 4
37 3
38 2
39 1
40 5
41 4
42 3
43 2
44 1
45 5
46 4
47 3
48 2
49 1
50 5
51 4
52 3
53 2
54 1
55 5
56 4
57 3
58 2
59 1
60 5
61 4
62 3
63 2
64 1
65 5
66 4
67 3
68 2
69 1
70 5
71 4
72 3
73 2
74 1
75 5
76 4
77 3
78 2
79 1
80 5
81 4
82 3
83 2
84 1
85 5
86 4
87 3
88 2
89 1
90 5
91 4
92 3
93 2
94 1
95 5
96 4
97 3
98 2
99 1
Simulation complete in 0.24s
Parts made: 19
Parts expected: 19

In [7]:
sys.machines[0].remaining_process_time

0

In [8]:
from random import random

In [11]:
for i in range(10): print(random())

0.5345258841255592
0.6999699135099143
0.6902940523618766
0.26946297347088743
0.6052170011870712
0.24339221047438664
0.2483099934414491
0.31544793269952787
0.9403281575280901
0.31221911911458644

In [12]:
degradation = 0.05

In [15]:
for i in range(20):
    print(random() > degradation)

True
True
True
True
True
True
True
True
True
False
True
True
True
True
False
True
True
True
True
True